language: r

sudo: required

cache: packages

os:
  - linux

# apt_packages:
#     - libmetis-dev
#     - libopenblas-dev
#     - liblapack-dev

jobs:
  include:
    - stage: Install and run tests
      r: 3.5
      script: 
        - bin/clone_and_install_pack.sh
        - bin/run_tests.sh
        


notifications:
  email:
    on_success: never
    on_failure: never
