language: r

sudo: required

cache: packages

os:
  - linux

# apt_packages:
#     - libmetis-dev
#     - libopenblas-dev
#     - liblapack-dev

jobs:
  include:
    - stage: Clone and install the package
      r: 3.5
      install: 
        - bin/clone_and_install_pack.sh
      script: true

    - stage: Run tests
      r: 3.5
      install: true
      script:
        - bin/run_tests.sh


notifications:
  email:
    on_success: never
    on_failure: never
